package pat;

public class pat_while_8
{
    public static void main(String[] args)
    {
        int i,j,k,n=3;
        System.out.println("---------------------------------------------------------------------");
        System.out.println("1-patten");
        i=0;
        while(i<n)
        {
            j=0;
            while(j<n)
            {
                System.out.print("*");
                j++;
            }
            i++;
            System.out.println();
        }
        System.out.println("---------------------------------------------------------------------");
        System.out.println("2-patten");
        i=1;
        while(i<=n)
        {
            j=1;
            while(j<=i)
            {
               System.out.print("*");
               j++;
            }
            System.out.println();
            i++;
        }
        System.out.println("---------------------------------------------------------------------");
        System.out.println("3-patten");
        i=0;
        while(i<n)
        {
            j=i;
            while(j<n)
            {
                System.out.print("*");
                j++;
            }
            i++;
            System.out.println();
        }
        System.out.println("---------------------------------------------------------------------");
        System.out.println("4-pattern");
        i=0;
        while(i<=2)
        {
            j=i;
            while(j<2)
            {
                System.out.print(" ");
                j++;
            }
            k=0;
            while(k<=i)
            {
                System.out.print("*");
                k++;
            }
            i++;
            System.out.println();
        }
        System.out.println("---------------------------------------------------------------------");
        System.out.println("5-pattern");
        i=0;
        while(i<3)
        {
            j=0;
            while(j<i)
            {
                System.out.print(" ");
                j++;
            }
            k=i;
            while(k<3)
            {
                System.out.print("*");
                k++;
            }
            i++;
            System.out.println();
        }
        System.out.println("---------------------------------------------------------------------");
        System.out.println("6-pattern");
        i=0;
        while(i<=2)
        {
            j=i;
            while(j<2)
            {
                System.out.print(" ");
                j++;
            }
            k=0;
            while(k<=i)
            {
                System.out.print("*");
                k++;
            }
            i++;
            System.out.println();
        }
        i=0;
        while(i<3)
        {
            j=0;
            while(j<i)
            {
                System.out.print(" ");
                j++;
            }
            k=i;
            while(k<3)
            {
                System.out.print("*");
                k++;
            }
            i++;
            System.out.println();
        }
        System.out.println("---------------------------------------------------------------------");
        System.out.println("7-pattern");
        i=0;
        while(i<=2)
        {
            j=i;
            while(j<2)
            {
                System.out.print(" ");
                j++;
            }
            k=0;
            while(k<=i)
            {
                System.out.print(" *");
                k++;
            }
            i++;
            System.out.println();
        }
        System.out.println("---------------------------------------------------------------------");
        System.out.println("8-pattern");
        i=1;
        while(i<=n)
        {
            j=i;
            while(j<n)
            {
                System.out.print(" ");
                j++;
            }
            k=1;
            while(k<=2*i-1)
            {
                System.out.print("*");
                k++;
            }
            i++;
            System.out.println();
        }
        System.out.println("---------------------------------------------------------------------");

    }
}
